"""
Utils package - Utility functions
"""
from .validators import (
    ValidationResult,
    validate_email,
    validate_phone,
    validate_required,
    validate_length,
    validate_number,
    validate_date,
    validate_date_range,
    validate_currency,
    validate_unique,
    validate_password,
    validate_form,
)

from .formatters import (
    format_currency,
    format_number,
    format_percentage,
    format_date,
    format_datetime,
    format_time,
    format_file_size,
    format_phone,
    format_address,
    format_name,
    format_duration,
    truncate_text,
    capitalize_words,
    slugify,
)

from .helpers import (
    generate_code,
    generate_id,
    get_project_root,
    get_data_dir,
    get_backup_dir,
    ensure_directory,
    backup_file,
    cleanup_old_backups,
    load_json_file,
    save_json_file,
    calculate_age,
    calculate_date_range,
    get_quarter,
    get_week_number,
    is_leap_year,
    get_days_in_month,
    safe_divide,
    clamp,
    interpolate,
    deep_merge,
    flatten_dict,
    group_by,
    sort_list,
    search_list,
    paginate_list,
)

__all__ = [
    # Validators
    'ValidationResult',
    'validate_email',
    'validate_phone',
    'validate_required',
    'validate_length',
    'validate_number',
    'validate_date',
    'validate_date_range',
    'validate_currency',
    'validate_unique',
    'validate_password',
    'validate_form',
    
    # Formatters
    'format_currency',
    'format_number',
    'format_percentage',
    'format_date',
    'format_datetime',
    'format_time',
    'format_file_size',
    'format_phone',
    'format_address',
    'format_name',
    'format_duration',
    'truncate_text',
    'capitalize_words',
    'slugify',
    
    # Helpers
    'generate_code',
    'generate_id',
    'get_project_root',
    'get_data_dir',
    'get_backup_dir',
    'ensure_directory',
    'backup_file',
    'cleanup_old_backups',
    'load_json_file',
    'save_json_file',
    'calculate_age',
    'calculate_date_range',
    'get_quarter',
    'get_week_number',
    'is_leap_year',
    'get_days_in_month',
    'safe_divide',
    'clamp',
    'interpolate',
    'deep_merge',
    'flatten_dict',
    'group_by',
    'sort_list',
    'search_list',
    'paginate_list',
]
